# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable"
        path: "internal"
        tables: "plugin_linapro_uidentity_cas_account,plugin_linapro_uidentity_cas_account_details,plugin_linapro_uidentity_cas_groups,plugin_linapro_uidentity_cas_units,plugin_linapro_uidentity_cas_containers,plugin_linapro_uidentity_cas_applications,plugin_linapro_uidentity_cas_account_group,plugin_linapro_uidentity_cas_account_unit,plugin_linapro_uidentity_cas_account_app_role,plugin_linapro_uidentity_cas_account_app_blacklist,plugin_linapro_uidentity_cas_group_app_blacklist,plugin_linapro_uidentity_cas_pass_ruler,plugin_linapro_uidentity_cas_sms,plugin_linapro_uidentity_cas_cas_login_log,plugin_linapro_uidentity_cas_oauth_log,plugin_linapro_uidentity_cas_oauth2_token,plugin_linapro_uidentity_cas_account_change_log,plugin_linapro_uidentity_cas_account_active_log"
        removePrefix: "plugin_linapro_uidentity_cas_"
        importPrefix: "lina-plugin-linapro-uidentity-cas/backend/internal"
        descriptionTag: true
        noModelComment: true
        stdTime: true
        typeMapping:
          timestamp:
            type: "*time.Time"
            import: time
          "timestamp without time zone":
            type: "*time.Time"
            import: time
          timestamptz:
            type: "*time.Time"
            import: time
          "timestamp with time zone":
            type: "*time.Time"
            import: time
