// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsAlbumImageDao is the data access object for the table plugin_cms_album_image.
// You can define custom methods on it to extend its functionality as needed.
type cmsAlbumImageDao struct {
	*internal.CmsAlbumImageDao
}

var (
	// CmsAlbumImage is a globally accessible object for table plugin_cms_album_image operations.
	CmsAlbumImage = cmsAlbumImageDao{internal.NewCmsAlbumImageDao()}
)

// Add your custom methods and functionality below.
