// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsMessageDao is the data access object for the table plugin_cms_message.
// You can define custom methods on it to extend its functionality as needed.
type cmsMessageDao struct {
	*internal.CmsMessageDao
}

var (
	// CmsMessage is a globally accessible object for table plugin_cms_message operations.
	CmsMessage = cmsMessageDao{internal.NewCmsMessageDao()}
)

// Add your custom methods and functionality below.
