// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsSiteDao is the data access object for the table plugin_cms_site.
// You can define custom methods on it to extend its functionality as needed.
type cmsSiteDao struct {
	*internal.CmsSiteDao
}

var (
	// CmsSite is a globally accessible object for table plugin_cms_site operations.
	CmsSite = cmsSiteDao{internal.NewCmsSiteDao()}
)

// Add your custom methods and functionality below.
