// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsCategoryDao is the data access object for the table plugin_cms_category.
// You can define custom methods on it to extend its functionality as needed.
type cmsCategoryDao struct {
	*internal.CmsCategoryDao
}

var (
	// CmsCategory is a globally accessible object for table plugin_cms_category operations.
	CmsCategory = cmsCategoryDao{internal.NewCmsCategoryDao()}
)

// Add your custom methods and functionality below.
