// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsArticleDao is the data access object for the table plugin_cms_article.
// You can define custom methods on it to extend its functionality as needed.
type cmsArticleDao struct {
	*internal.CmsArticleDao
}

var (
	// CmsArticle is a globally accessible object for table plugin_cms_article operations.
	CmsArticle = cmsArticleDao{internal.NewCmsArticleDao()}
)

// Add your custom methods and functionality below.
