// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsLinkDao is the data access object for the table plugin_cms_link.
// You can define custom methods on it to extend its functionality as needed.
type cmsLinkDao struct {
	*internal.CmsLinkDao
}

var (
	// CmsLink is a globally accessible object for table plugin_cms_link operations.
	CmsLink = cmsLinkDao{internal.NewCmsLinkDao()}
)

// Add your custom methods and functionality below.
