// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsSlideDao is the data access object for the table plugin_cms_slide.
// You can define custom methods on it to extend its functionality as needed.
type cmsSlideDao struct {
	*internal.CmsSlideDao
}

var (
	// CmsSlide is a globally accessible object for table plugin_cms_slide operations.
	CmsSlide = cmsSlideDao{internal.NewCmsSlideDao()}
)

// Add your custom methods and functionality below.
