// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsProductDao is the data access object for the table plugin_cms_product.
// You can define custom methods on it to extend its functionality as needed.
type cmsProductDao struct {
	*internal.CmsProductDao
}

var (
	// CmsProduct is a globally accessible object for table plugin_cms_product operations.
	CmsProduct = cmsProductDao{internal.NewCmsProductDao()}
)

// Add your custom methods and functionality below.
