// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-cms/backend/internal/dao/internal"
)

// cmsArticleTagDao is the data access object for the table plugin_cms_article_tag.
// You can define custom methods on it to extend its functionality as needed.
type cmsArticleTagDao struct {
	*internal.CmsArticleTagDao
}

var (
	// CmsArticleTag is a globally accessible object for table plugin_cms_article_tag operations.
	CmsArticleTag = cmsArticleTagDao{internal.NewCmsArticleTagDao()}
)

// Add your custom methods and functionality below.
