// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package water

import (
	"lina-plugin-water/backend/api/water"
	watersvc "lina-plugin-water/backend/internal/service/water"
)

// ControllerV1 is the water plugin controller.
type ControllerV1 struct {
	waterSvc watersvc.Service // waterSvc handles watermark business operations.
}

// NewV1 creates and returns a new water controller instance.
func NewV1() water.IWaterV1 {
	return &ControllerV1{waterSvc: watersvc.New()}
}
