// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-water/backend/internal/dao/internal"
)

// mediaStrategyDeviceTenantDao is the data access object for the table media_strategy_device_tenant.
// You can define custom methods on it to extend its functionality as needed.
type mediaStrategyDeviceTenantDao struct {
	*internal.MediaStrategyDeviceTenantDao
}

var (
	// MediaStrategyDeviceTenant is a globally accessible object for table media_strategy_device_tenant operations.
	MediaStrategyDeviceTenant = mediaStrategyDeviceTenantDao{internal.NewMediaStrategyDeviceTenantDao()}
)

// Add your custom methods and functionality below.
