// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-water/backend/internal/dao/internal"
)

// mediaStrategyDeviceDao is the data access object for the table media_strategy_device.
// You can define custom methods on it to extend its functionality as needed.
type mediaStrategyDeviceDao struct {
	*internal.MediaStrategyDeviceDao
}

var (
	// MediaStrategyDevice is a globally accessible object for table media_strategy_device operations.
	MediaStrategyDevice = mediaStrategyDeviceDao{internal.NewMediaStrategyDeviceDao()}
)

// Add your custom methods and functionality below.
