// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// activationDao is the data access object for the table plugin_sicau_niu_activation.
// You can define custom methods on it to extend its functionality as needed.
type activationDao struct {
	*internal.ActivationDao
}

var (
	// Activation is a globally accessible object for table plugin_sicau_niu_activation operations.
	Activation = activationDao{internal.NewActivationDao()}
)

// Add your custom methods and functionality below.
