// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// activationPhotoDao is the data access object for the table plugin_sicau_niu_activation_photo.
// You can define custom methods on it to extend its functionality as needed.
type activationPhotoDao struct {
	*internal.ActivationPhotoDao
}

var (
	// ActivationPhoto is a globally accessible object for table plugin_sicau_niu_activation_photo operations.
	ActivationPhoto = activationPhotoDao{internal.NewActivationPhotoDao()}
)

// Add your custom methods and functionality below.
