// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// activationAttemptDao is the data access object for the table plugin_sicau_niu_activation_attempt.
// You can define custom methods on it to extend its functionality as needed.
type activationAttemptDao struct {
	*internal.ActivationAttemptDao
}

var (
	// ActivationAttempt is a globally accessible object for table plugin_sicau_niu_activation_attempt operations.
	ActivationAttempt = activationAttemptDao{internal.NewActivationAttemptDao()}
)

// Add your custom methods and functionality below.
