// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// cardDao is the data access object for the table plugin_sicau_niu_card.
// You can define custom methods on it to extend its functionality as needed.
type cardDao struct {
	*internal.CardDao
}

var (
	// Card is a globally accessible object for table plugin_sicau_niu_card operations.
	Card = cardDao{internal.NewCardDao()}
)

// Add your custom methods and functionality below.
