// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// checkinDao is the data access object for the table plugin_sicau_niu_checkin.
// You can define custom methods on it to extend its functionality as needed.
type checkinDao struct {
	*internal.CheckinDao
}

var (
	// Checkin is a globally accessible object for table plugin_sicau_niu_checkin operations.
	Checkin = checkinDao{internal.NewCheckinDao()}
)

// Add your custom methods and functionality below.
