// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// feedingDao is the data access object for the table plugin_sicau_niu_feeding.
// You can define custom methods on it to extend its functionality as needed.
type feedingDao struct {
	*internal.FeedingDao
}

var (
	// Feeding is a globally accessible object for table plugin_sicau_niu_feeding operations.
	Feeding = feedingDao{internal.NewFeedingDao()}
)

// Add your custom methods and functionality below.
