// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// giftDao is the data access object for the table plugin_sicau_niu_gift.
// You can define custom methods on it to extend its functionality as needed.
type giftDao struct {
	*internal.GiftDao
}

var (
	// Gift is a globally accessible object for table plugin_sicau_niu_gift operations.
	Gift = giftDao{internal.NewGiftDao()}
)

// Add your custom methods and functionality below.
