// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// grassAccountDao is the data access object for the table plugin_sicau_niu_grass_account.
// You can define custom methods on it to extend its functionality as needed.
type grassAccountDao struct {
	*internal.GrassAccountDao
}

var (
	// GrassAccount is a globally accessible object for table plugin_sicau_niu_grass_account operations.
	GrassAccount = grassAccountDao{internal.NewGrassAccountDao()}
)

// Add your custom methods and functionality below.
