// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// grassTxnDao is the data access object for the table plugin_sicau_niu_grass_txn.
// You can define custom methods on it to extend its functionality as needed.
type grassTxnDao struct {
	*internal.GrassTxnDao
}

var (
	// GrassTxn is a globally accessible object for table plugin_sicau_niu_grass_txn operations.
	GrassTxn = grassTxnDao{internal.NewGrassTxnDao()}
)

// Add your custom methods and functionality below.
