// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// honorDefDao is the data access object for the table plugin_sicau_niu_honor_def.
// You can define custom methods on it to extend its functionality as needed.
type honorDefDao struct {
	*internal.HonorDefDao
}

var (
	// HonorDef is a globally accessible object for table plugin_sicau_niu_honor_def operations.
	HonorDef = honorDefDao{internal.NewHonorDefDao()}
)

// Add your custom methods and functionality below.
