// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// inboxMsgDao is the data access object for the table plugin_sicau_niu_inbox_msg.
// You can define custom methods on it to extend its functionality as needed.
type inboxMsgDao struct {
	*internal.InboxMsgDao
}

var (
	// InboxMsg is a globally accessible object for table plugin_sicau_niu_inbox_msg operations.
	InboxMsg = inboxMsgDao{internal.NewInboxMsgDao()}
)

// Add your custom methods and functionality below.
