// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// ironDao is the data access object for the table plugin_sicau_niu_iron.
// You can define custom methods on it to extend its functionality as needed.
type ironDao struct {
	*internal.IronDao
}

var (
	// Iron is a globally accessible object for table plugin_sicau_niu_iron operations.
	Iron = ironDao{internal.NewIronDao()}
)

// Add your custom methods and functionality below.
