// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// miniappConfigDao is the data access object for the table plugin_sicau_niu_miniapp_config.
// You can define custom methods on it to extend its functionality as needed.
type miniappConfigDao struct {
	*internal.MiniappConfigDao
}

var (
	// MiniappConfig is a globally accessible object for table plugin_sicau_niu_miniapp_config operations.
	MiniappConfig = miniappConfigDao{internal.NewMiniappConfigDao()}
)

// Add your custom methods and functionality below.
