// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// niuDao is the data access object for the table plugin_sicau_niu_niu.
// You can define custom methods on it to extend its functionality as needed.
type niuDao struct {
	*internal.NiuDao
}

var (
	// Niu is a globally accessible object for table plugin_sicau_niu_niu operations.
	Niu = niuDao{internal.NewNiuDao()}
)

// Add your custom methods and functionality below.
