// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// quoteDao is the data access object for the table plugin_sicau_niu_quote.
// You can define custom methods on it to extend its functionality as needed.
type quoteDao struct {
	*internal.QuoteDao
}

var (
	// Quote is a globally accessible object for table plugin_sicau_niu_quote operations.
	Quote = quoteDao{internal.NewQuoteDao()}
)

// Add your custom methods and functionality below.
