// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// ruleConfigDao is the data access object for the table plugin_sicau_niu_rule_config.
// You can define custom methods on it to extend its functionality as needed.
type ruleConfigDao struct {
	*internal.RuleConfigDao
}

var (
	// RuleConfig is a globally accessible object for table plugin_sicau_niu_rule_config operations.
	RuleConfig = ruleConfigDao{internal.NewRuleConfigDao()}
)

// Add your custom methods and functionality below.
