// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// settlementDao is the data access object for the table plugin_sicau_niu_settlement.
// You can define custom methods on it to extend its functionality as needed.
type settlementDao struct {
	*internal.SettlementDao
}

var (
	// Settlement is a globally accessible object for table plugin_sicau_niu_settlement operations.
	Settlement = settlementDao{internal.NewSettlementDao()}
)

// Add your custom methods and functionality below.
