// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// stealDao is the data access object for the table plugin_sicau_niu_steal.
// You can define custom methods on it to extend its functionality as needed.
type stealDao struct {
	*internal.StealDao
}

var (
	// Steal is a globally accessible object for table plugin_sicau_niu_steal operations.
	Steal = stealDao{internal.NewStealDao()}
)

// Add your custom methods and functionality below.
