// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// transportTeamDao is the data access object for the table plugin_sicau_niu_transport_team.
// You can define custom methods on it to extend its functionality as needed.
type transportTeamDao struct {
	*internal.TransportTeamDao
}

var (
	// TransportTeam is a globally accessible object for table plugin_sicau_niu_transport_team operations.
	TransportTeam = transportTeamDao{internal.NewTransportTeamDao()}
)

// Add your custom methods and functionality below.
