// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// transportReportDao is the data access object for the table plugin_sicau_niu_transport_report.
// You can define custom methods on it to extend its functionality as needed.
type transportReportDao struct {
	*internal.TransportReportDao
}

var (
	// TransportReport is a globally accessible object for table plugin_sicau_niu_transport_report operations.
	TransportReport = transportReportDao{internal.NewTransportReportDao()}
)

// Add your custom methods and functionality below.
