// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// transportTrackDao is the data access object for the table plugin_sicau_niu_transport_track.
// You can define custom methods on it to extend its functionality as needed.
type transportTrackDao struct {
	*internal.TransportTrackDao
}

var (
	// TransportTrack is a globally accessible object for table plugin_sicau_niu_transport_track operations.
	TransportTrack = transportTrackDao{internal.NewTransportTrackDao()}
)

// Add your custom methods and functionality below.
