// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// transportSessionDao is the data access object for the table plugin_sicau_niu_transport_session.
// You can define custom methods on it to extend its functionality as needed.
type transportSessionDao struct {
	*internal.TransportSessionDao
}

var (
	// TransportSession is a globally accessible object for table plugin_sicau_niu_transport_session operations.
	TransportSession = transportSessionDao{internal.NewTransportSessionDao()}
)

// Add your custom methods and functionality below.
