// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// transportMemberDao is the data access object for the table plugin_sicau_niu_transport_member.
// You can define custom methods on it to extend its functionality as needed.
type transportMemberDao struct {
	*internal.TransportMemberDao
}

var (
	// TransportMember is a globally accessible object for table plugin_sicau_niu_transport_member operations.
	TransportMember = transportMemberDao{internal.NewTransportMemberDao()}
)

// Add your custom methods and functionality below.
