// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-sicau-niu/backend/internal/dao/internal"
)

// userHonorDao is the data access object for the table plugin_sicau_niu_user_honor.
// You can define custom methods on it to extend its functionality as needed.
type userHonorDao struct {
	*internal.UserHonorDao
}

var (
	// UserHonor is a globally accessible object for table plugin_sicau_niu_user_honor operations.
	UserHonor = userHonorDao{internal.NewUserHonorDao()}
)

// Add your custom methods and functionality below.
