// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-extlogin-core/backend/internal/dao/internal"
)

// userExternalIdentityDao is the data access object for the table plugin_linapro_extlogin_core_user_external_identity.
// You can define custom methods on it to extend its functionality as needed.
type userExternalIdentityDao struct {
	*internal.UserExternalIdentityDao
}

var (
	// UserExternalIdentity is a globally accessible object for table plugin_linapro_extlogin_core_user_external_identity operations.
	UserExternalIdentity = userExternalIdentityDao{internal.NewUserExternalIdentityDao()}
)

// Add your custom methods and functionality below.
