// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountAppBlacklistDao is the data access object for the table plugin_linapro_uidentity_cas_account_app_blacklist.
// You can define custom methods on it to extend its functionality as needed.
type accountAppBlacklistDao struct {
	*internal.AccountAppBlacklistDao
}

var (
	// AccountAppBlacklist is a globally accessible object for table plugin_linapro_uidentity_cas_account_app_blacklist operations.
	AccountAppBlacklist = accountAppBlacklistDao{internal.NewAccountAppBlacklistDao()}
)

// Add your custom methods and functionality below.
