// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountUnitDao is the data access object for the table plugin_linapro_uidentity_cas_account_unit.
// You can define custom methods on it to extend its functionality as needed.
type accountUnitDao struct {
	*internal.AccountUnitDao
}

var (
	// AccountUnit is a globally accessible object for table plugin_linapro_uidentity_cas_account_unit operations.
	AccountUnit = accountUnitDao{internal.NewAccountUnitDao()}
)

// Add your custom methods and functionality below.
