// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountDetailDao is the data access object for the table plugin_linapro_uidentity_cas_account_detail.
// You can define custom methods on it to extend its functionality as needed.
type accountDetailDao struct {
	*internal.AccountDetailDao
}

var (
	// AccountDetail is a globally accessible object for table plugin_linapro_uidentity_cas_account_detail operations.
	AccountDetail = accountDetailDao{internal.NewAccountDetailDao()}
)

// Add your custom methods and functionality below.
