// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountDetailsDao is the data access object for the table account_details.
// You can define custom methods on it to extend its functionality as needed.
type accountDetailsDao struct {
	*internal.AccountDetailsDao
}

var (
	// AccountDetails is a globally accessible object for table account_details operations.
	AccountDetails = accountDetailsDao{internal.NewAccountDetailsDao()}
)

// Add your custom methods and functionality below.
