// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountActiveLogDao is the data access object for the table plugin_linapro_uidentity_cas_account_active_log.
// You can define custom methods on it to extend its functionality as needed.
type accountActiveLogDao struct {
	*internal.AccountActiveLogDao
}

var (
	// AccountActiveLog is a globally accessible object for table plugin_linapro_uidentity_cas_account_active_log operations.
	AccountActiveLog = accountActiveLogDao{internal.NewAccountActiveLogDao()}
)

// Add your custom methods and functionality below.
