// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountChangeLogDao is the data access object for the table plugin_linapro_uidentity_cas_account_change_log.
// You can define custom methods on it to extend its functionality as needed.
type accountChangeLogDao struct {
	*internal.AccountChangeLogDao
}

var (
	// AccountChangeLog is a globally accessible object for table plugin_linapro_uidentity_cas_account_change_log operations.
	AccountChangeLog = accountChangeLogDao{internal.NewAccountChangeLogDao()}
)

// Add your custom methods and functionality below.
