// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountGroupDao is the data access object for the table plugin_linapro_uidentity_cas_account_group.
// You can define custom methods on it to extend its functionality as needed.
type accountGroupDao struct {
	*internal.AccountGroupDao
}

var (
	// AccountGroup is a globally accessible object for table plugin_linapro_uidentity_cas_account_group operations.
	AccountGroup = accountGroupDao{internal.NewAccountGroupDao()}
)

// Add your custom methods and functionality below.
