// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// accountDao is the data access object for the table plugin_linapro_uidentity_cas_account.
// You can define custom methods on it to extend its functionality as needed.
type accountDao struct {
	*internal.AccountDao
}

var (
	// Account is a globally accessible object for table plugin_linapro_uidentity_cas_account operations.
	Account = accountDao{internal.NewAccountDao()}
)

// Add your custom methods and functionality below.
