// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// applicationDao is the data access object for the table plugin_linapro_uidentity_cas_application.
// You can define custom methods on it to extend its functionality as needed.
type applicationDao struct {
	*internal.ApplicationDao
}

var (
	// Application is a globally accessible object for table plugin_linapro_uidentity_cas_application operations.
	Application = applicationDao{internal.NewApplicationDao()}
)

// Add your custom methods and functionality below.
