// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// applicationsDao is the data access object for the table applications.
// You can define custom methods on it to extend its functionality as needed.
type applicationsDao struct {
	*internal.ApplicationsDao
}

var (
	// Applications is a globally accessible object for table applications operations.
	Applications = applicationsDao{internal.NewApplicationsDao()}
)

// Add your custom methods and functionality below.
