// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// casLoginLogDao is the data access object for the table plugin_linapro_uidentity_cas_cas_login_log.
// You can define custom methods on it to extend its functionality as needed.
type casLoginLogDao struct {
	*internal.CasLoginLogDao
}

var (
	// CasLoginLog is a globally accessible object for table plugin_linapro_uidentity_cas_cas_login_log operations.
	CasLoginLog = casLoginLogDao{internal.NewCasLoginLogDao()}
)

// Add your custom methods and functionality below.
