// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// containersDao is the data access object for the table containers.
// You can define custom methods on it to extend its functionality as needed.
type containersDao struct {
	*internal.ContainersDao
}

var (
	// Containers is a globally accessible object for table containers operations.
	Containers = containersDao{internal.NewContainersDao()}
)

// Add your custom methods and functionality below.
