// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// containerDao is the data access object for the table plugin_linapro_uidentity_cas_container.
// You can define custom methods on it to extend its functionality as needed.
type containerDao struct {
	*internal.ContainerDao
}

var (
	// Container is a globally accessible object for table plugin_linapro_uidentity_cas_container operations.
	Container = containerDao{internal.NewContainerDao()}
)

// Add your custom methods and functionality below.
