// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// groupsDao is the data access object for the table groups.
// You can define custom methods on it to extend its functionality as needed.
type groupsDao struct {
	*internal.GroupsDao
}

var (
	// Groups is a globally accessible object for table groups operations.
	Groups = groupsDao{internal.NewGroupsDao()}
)

// Add your custom methods and functionality below.
