// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// groupDao is the data access object for the table plugin_linapro_uidentity_cas_group.
// You can define custom methods on it to extend its functionality as needed.
type groupDao struct {
	*internal.GroupDao
}

var (
	// Group is a globally accessible object for table plugin_linapro_uidentity_cas_group operations.
	Group = groupDao{internal.NewGroupDao()}
)

// Add your custom methods and functionality below.
