// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// jobLogDao is the data access object for the table plugin_linapro_uidentity_cas_job_log.
// You can define custom methods on it to extend its functionality as needed.
type jobLogDao struct {
	*internal.JobLogDao
}

var (
	// JobLog is a globally accessible object for table plugin_linapro_uidentity_cas_job_log operations.
	JobLog = jobLogDao{internal.NewJobLogDao()}
)

// Add your custom methods and functionality below.
