// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// oauthLogDao is the data access object for the table plugin_linapro_uidentity_cas_oauth_log.
// You can define custom methods on it to extend its functionality as needed.
type oauthLogDao struct {
	*internal.OauthLogDao
}

var (
	// OauthLog is a globally accessible object for table plugin_linapro_uidentity_cas_oauth_log operations.
	OauthLog = oauthLogDao{internal.NewOauthLogDao()}
)

// Add your custom methods and functionality below.
