// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// oauth2TokenDao is the data access object for the table oauth2_token.
// You can define custom methods on it to extend its functionality as needed.
type oauth2TokenDao struct {
	*internal.Oauth2TokenDao
}

var (
	// Oauth2Token is a globally accessible object for table oauth2_token operations.
	Oauth2Token = oauth2TokenDao{internal.NewOauth2TokenDao()}
)

// Add your custom methods and functionality below.
