// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// oauthTokenDao is the data access object for the table plugin_linapro_uidentity_cas_oauth_token.
// You can define custom methods on it to extend its functionality as needed.
type oauthTokenDao struct {
	*internal.OauthTokenDao
}

var (
	// OauthToken is a globally accessible object for table plugin_linapro_uidentity_cas_oauth_token operations.
	OauthToken = oauthTokenDao{internal.NewOauthTokenDao()}
)

// Add your custom methods and functionality below.
