// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// passRuleDao is the data access object for the table plugin_linapro_uidentity_cas_pass_rule.
// You can define custom methods on it to extend its functionality as needed.
type passRuleDao struct {
	*internal.PassRuleDao
}

var (
	// PassRule is a globally accessible object for table plugin_linapro_uidentity_cas_pass_rule operations.
	PassRule = passRuleDao{internal.NewPassRuleDao()}
)

// Add your custom methods and functionality below.
