// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// passRulerDao is the data access object for the table pass_ruler.
// You can define custom methods on it to extend its functionality as needed.
type passRulerDao struct {
	*internal.PassRulerDao
}

var (
	// PassRuler is a globally accessible object for table pass_ruler operations.
	PassRuler = passRulerDao{internal.NewPassRulerDao()}
)

// Add your custom methods and functionality below.
