// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// smsDao is the data access object for the table plugin_linapro_uidentity_cas_sms.
// You can define custom methods on it to extend its functionality as needed.
type smsDao struct {
	*internal.SmsDao
}

var (
	// Sms is a globally accessible object for table plugin_linapro_uidentity_cas_sms operations.
	Sms = smsDao{internal.NewSmsDao()}
)

// Add your custom methods and functionality below.
