// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysTablesDao is the data access object for the table plugin_linapro_uidentity_cas_sys_tables.
// You can define custom methods on it to extend its functionality as needed.
type sysTablesDao struct {
	*internal.SysTablesDao
}

var (
	// SysTables is a globally accessible object for table plugin_linapro_uidentity_cas_sys_tables operations.
	SysTables = sysTablesDao{internal.NewSysTablesDao()}
)

// Add your custom methods and functionality below.
