// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysJobDao is the data access object for the table plugin_linapro_uidentity_cas_sys_job.
// You can define custom methods on it to extend its functionality as needed.
type sysJobDao struct {
	*internal.SysJobDao
}

var (
	// SysJob is a globally accessible object for table plugin_linapro_uidentity_cas_sys_job operations.
	SysJob = sysJobDao{internal.NewSysJobDao()}
)

// Add your custom methods and functionality below.
