// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysDictDataDao is the data access object for the table plugin_linapro_uidentity_cas_sys_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type sysDictDataDao struct {
	*internal.SysDictDataDao
}

var (
	// SysDictData is a globally accessible object for table plugin_linapro_uidentity_cas_sys_dict_data operations.
	SysDictData = sysDictDataDao{internal.NewSysDictDataDao()}
)

// Add your custom methods and functionality below.
