// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysRoleMenuDao is the data access object for the table plugin_linapro_uidentity_cas_sys_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleMenuDao struct {
	*internal.SysRoleMenuDao
}

var (
	// SysRoleMenu is a globally accessible object for table plugin_linapro_uidentity_cas_sys_role_menu operations.
	SysRoleMenu = sysRoleMenuDao{internal.NewSysRoleMenuDao()}
)

// Add your custom methods and functionality below.
