// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysRoleDeptDao is the data access object for the table plugin_linapro_uidentity_cas_sys_role_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleDeptDao struct {
	*internal.SysRoleDeptDao
}

var (
	// SysRoleDept is a globally accessible object for table plugin_linapro_uidentity_cas_sys_role_dept operations.
	SysRoleDept = sysRoleDeptDao{internal.NewSysRoleDeptDao()}
)

// Add your custom methods and functionality below.
