// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysColumnsDao is the data access object for the table plugin_linapro_uidentity_cas_sys_columns.
// You can define custom methods on it to extend its functionality as needed.
type sysColumnsDao struct {
	*internal.SysColumnsDao
}

var (
	// SysColumns is a globally accessible object for table plugin_linapro_uidentity_cas_sys_columns operations.
	SysColumns = sysColumnsDao{internal.NewSysColumnsDao()}
)

// Add your custom methods and functionality below.
