// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysCasbinRuleDao is the data access object for the table plugin_linapro_uidentity_cas_sys_casbin_rule.
// You can define custom methods on it to extend its functionality as needed.
type sysCasbinRuleDao struct {
	*internal.SysCasbinRuleDao
}

var (
	// SysCasbinRule is a globally accessible object for table plugin_linapro_uidentity_cas_sys_casbin_rule operations.
	SysCasbinRule = sysCasbinRuleDao{internal.NewSysCasbinRuleDao()}
)

// Add your custom methods and functionality below.
