// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysMenuDao is the data access object for the table plugin_linapro_uidentity_cas_sys_menu.
// You can define custom methods on it to extend its functionality as needed.
type sysMenuDao struct {
	*internal.SysMenuDao
}

var (
	// SysMenu is a globally accessible object for table plugin_linapro_uidentity_cas_sys_menu operations.
	SysMenu = sysMenuDao{internal.NewSysMenuDao()}
)

// Add your custom methods and functionality below.
