// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysMenuApiRuleDao is the data access object for the table plugin_linapro_uidentity_cas_sys_menu_api_rule.
// You can define custom methods on it to extend its functionality as needed.
type sysMenuApiRuleDao struct {
	*internal.SysMenuApiRuleDao
}

var (
	// SysMenuApiRule is a globally accessible object for table plugin_linapro_uidentity_cas_sys_menu_api_rule operations.
	SysMenuApiRule = sysMenuApiRuleDao{internal.NewSysMenuApiRuleDao()}
)

// Add your custom methods and functionality below.
