// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// sysPostDao is the data access object for the table plugin_linapro_uidentity_cas_sys_post.
// You can define custom methods on it to extend its functionality as needed.
type sysPostDao struct {
	*internal.SysPostDao
}

var (
	// SysPost is a globally accessible object for table plugin_linapro_uidentity_cas_sys_post operations.
	SysPost = sysPostDao{internal.NewSysPostDao()}
)

// Add your custom methods and functionality below.
