// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-uidentity-cas/backend/internal/dao/internal"
)

// unitsDao is the data access object for the table units.
// You can define custom methods on it to extend its functionality as needed.
type unitsDao struct {
	*internal.UnitsDao
}

var (
	// Units is a globally accessible object for table units operations.
	Units = unitsDao{internal.NewUnitsDao()}
)

// Add your custom methods and functionality below.
