// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package uidentity

import (
	uidentityapi "lina-plugin-linapro-uidentity-cas/backend/api/uidentity"
	uidentitysvc "lina-plugin-linapro-uidentity-cas/backend/internal/service/uidentity"
)

// ControllerV1 serves backend-only UIdentity CAS HTTP APIs.
type ControllerV1 struct {
	uidentitySvc uidentitysvc.Service // UIdentity CAS domain service.
}

// NewV1 creates a new UIdentity CAS controller.
func NewV1(uidentitySvc uidentitysvc.Service) uidentityapi.IUidentityV1 {
	return &ControllerV1{uidentitySvc: uidentitySvc}
}
