// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaReportNodeSnapshotDao is the data access object for the table media_report_node_snapshot.
// You can define custom methods on it to extend its functionality as needed.
type mediaReportNodeSnapshotDao struct {
	*internal.MediaReportNodeSnapshotDao
}

var (
	// MediaReportNodeSnapshot is a globally accessible object for table media_report_node_snapshot operations.
	MediaReportNodeSnapshot = mediaReportNodeSnapshotDao{internal.NewMediaReportNodeSnapshotDao()}
)

// Add your custom methods and functionality below.
