// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaReportSessionDao is the data access object for the table media_report_session.
// You can define custom methods on it to extend its functionality as needed.
type mediaReportSessionDao struct {
	*internal.MediaReportSessionDao
}

var (
	// MediaReportSession is a globally accessible object for table media_report_session operations.
	MediaReportSession = mediaReportSessionDao{internal.NewMediaReportSessionDao()}
)

// Add your custom methods and functionality below.
