// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaTenantWhiteDao is the data access object for the table media_tenant_white.
// You can define custom methods on it to extend its functionality as needed.
type mediaTenantWhiteDao struct {
	*internal.MediaTenantWhiteDao
}

var (
	// MediaTenantWhite is a globally accessible object for table media_tenant_white operations.
	MediaTenantWhite = mediaTenantWhiteDao{internal.NewMediaTenantWhiteDao()}
)

// Add your custom methods and functionality below.
