// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaStreamAliasDao is the data access object for the table media_stream_alias.
// You can define custom methods on it to extend its functionality as needed.
type mediaStreamAliasDao struct {
	*internal.MediaStreamAliasDao
}

var (
	// MediaStreamAlias is a globally accessible object for table media_stream_alias operations.
	MediaStreamAlias = mediaStreamAliasDao{internal.NewMediaStreamAliasDao()}
)

// Add your custom methods and functionality below.
