// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaTenantStreamConfigDao is the data access object for the table media_tenant_stream_config.
// You can define custom methods on it to extend its functionality as needed.
type mediaTenantStreamConfigDao struct {
	*internal.MediaTenantStreamConfigDao
}

var (
	// MediaTenantStreamConfig is a globally accessible object for table media_tenant_stream_config operations.
	MediaTenantStreamConfig = mediaTenantStreamConfigDao{internal.NewMediaTenantStreamConfigDao()}
)

// Add your custom methods and functionality below.
