// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaStrategyDao is the data access object for the table media_strategy.
// You can define custom methods on it to extend its functionality as needed.
type mediaStrategyDao struct {
	*internal.MediaStrategyDao
}

var (
	// MediaStrategy is a globally accessible object for table media_strategy operations.
	MediaStrategy = mediaStrategyDao{internal.NewMediaStrategyDao()}
)

// Add your custom methods and functionality below.
