// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaReportStreamDao is the data access object for the table media_report_stream.
// You can define custom methods on it to extend its functionality as needed.
type mediaReportStreamDao struct {
	*internal.MediaReportStreamDao
}

var (
	// MediaReportStream is a globally accessible object for table media_report_stream operations.
	MediaReportStream = mediaReportStreamDao{internal.NewMediaReportStreamDao()}
)

// Add your custom methods and functionality below.
