// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaReportNodeDao is the data access object for the table media_report_node.
// You can define custom methods on it to extend its functionality as needed.
type mediaReportNodeDao struct {
	*internal.MediaReportNodeDao
}

var (
	// MediaReportNode is a globally accessible object for table media_report_node operations.
	MediaReportNode = mediaReportNodeDao{internal.NewMediaReportNodeDao()}
)

// Add your custom methods and functionality below.
