// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaStrategyTenantDao is the data access object for the table media_strategy_tenant.
// You can define custom methods on it to extend its functionality as needed.
type mediaStrategyTenantDao struct {
	*internal.MediaStrategyTenantDao
}

var (
	// MediaStrategyTenant is a globally accessible object for table media_strategy_tenant operations.
	MediaStrategyTenant = mediaStrategyTenantDao{internal.NewMediaStrategyTenantDao()}
)

// Add your custom methods and functionality below.
