// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaDeviceNodeDao is the data access object for the table media_device_node.
// You can define custom methods on it to extend its functionality as needed.
type mediaDeviceNodeDao struct {
	*internal.MediaDeviceNodeDao
}

var (
	// MediaDeviceNode is a globally accessible object for table media_device_node operations.
	MediaDeviceNode = mediaDeviceNodeDao{internal.NewMediaDeviceNodeDao()}
)

// Add your custom methods and functionality below.
