// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaNodeDao is the data access object for the table media_node.
// You can define custom methods on it to extend its functionality as needed.
type mediaNodeDao struct {
	*internal.MediaNodeDao
}

var (
	// MediaNode is a globally accessible object for table media_node operations.
	MediaNode = mediaNodeDao{internal.NewMediaNodeDao()}
)

// Add your custom methods and functionality below.
