// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// mediaReportInstanceDao is the data access object for the table media_report_instance.
// You can define custom methods on it to extend its functionality as needed.
type mediaReportInstanceDao struct {
	*internal.MediaReportInstanceDao
}

var (
	// MediaReportInstance is a globally accessible object for table media_report_instance operations.
	MediaReportInstance = mediaReportInstanceDao{internal.NewMediaReportInstanceDao()}
)

// Add your custom methods and functionality below.
