// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-mail-core/backend/internal/dao/internal"
)

// accountDao is the data access object for the table plugin_linapro_mail_core_account.
type accountDao struct {
	*internal.AccountDao
}

var (
	// Account is a globally accessible object for table plugin_linapro_mail_core_account operations.
	Account = accountDao{internal.NewAccountDao()}
)
