// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-mail-core/backend/internal/dao/internal"
)

// connectionDao is the data access object for the table plugin_linapro_mail_core_connection.
type connectionDao struct {
	*internal.ConnectionDao
}

var (
	// Connection is a globally accessible object for table plugin_linapro_mail_core_connection operations.
	Connection = connectionDao{internal.NewConnectionDao()}
)
