// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// sysPluginStateDao is the data access object for the table sys_plugin_state.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginStateDao struct {
	*internal.SysPluginStateDao
}

var (
	// SysPluginState is a globally accessible object for table sys_plugin_state operations.
	SysPluginState = sysPluginStateDao{internal.NewSysPluginStateDao()}
)

// Add your custom methods and functionality below.
