// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// sysPluginDao is the data access object for the table sys_plugin.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginDao struct {
	*internal.SysPluginDao
}

var (
	// SysPlugin is a globally accessible object for table sys_plugin operations.
	SysPlugin = sysPluginDao{internal.NewSysPluginDao()}
)

// Add your custom methods and functionality below.
