// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package niu

import (
	niusvc "lina-plugin-sicau-niu/backend/internal/service/niu"
)

// ControllerV1 is the sicau-niu controller.
type ControllerV1 struct {
	niuSvc niusvc.Service // niuSvc orchestrates the sicau-niu sample data.
}

// NewV1 creates and returns a new sicau-niu controller instance.
func NewV1(niuSvc niusvc.Service) *ControllerV1 {
	return &ControllerV1{niuSvc: niuSvc}
}
