# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable&search_path=public"
        path: "internal"
        tables: "media_strategy,media_strategy_device,media_strategy_device_tenant,media_strategy_tenant"
        importPrefix: "lina-plugin-water/backend/internal"
        descriptionTag: true
        noModelComment: true
