// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-monitor-online/backend/internal/dao/internal"
)

// sysOnlineSessionDao is the data access object for the table sys_online_session.
// You can define custom methods on it to extend its functionality as needed.
type sysOnlineSessionDao struct {
	*internal.SysOnlineSessionDao
}

var (
	// SysOnlineSession is a globally accessible object for table sys_online_session operations.
	SysOnlineSession = sysOnlineSessionDao{internal.NewSysOnlineSessionDao()}
)

// Add your custom methods and functionality below.
