# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable"
        path: "internal"
        tables: "plugin_sicau_niu_user,plugin_sicau_niu_college,plugin_sicau_niu_niu,plugin_sicau_niu_iron,plugin_sicau_niu_card,plugin_sicau_niu_quote,plugin_sicau_niu_activation,plugin_sicau_niu_activation_attempt,plugin_sicau_niu_activation_photo,plugin_sicau_niu_miniapp_config,plugin_sicau_niu_grass_account,plugin_sicau_niu_grass_txn,plugin_sicau_niu_checkin,plugin_sicau_niu_feeding,plugin_sicau_niu_steal,plugin_sicau_niu_gift,plugin_sicau_niu_inbox_msg,plugin_sicau_niu_honor_def,plugin_sicau_niu_user_honor,plugin_sicau_niu_settlement,plugin_sicau_niu_rule_config,plugin_sicau_niu_transport_team,plugin_sicau_niu_transport_member,plugin_sicau_niu_transport_report"
        removePrefix: "plugin_sicau_niu_"
        importPrefix: "lina-plugin-sicau-niu/backend/internal"
        descriptionTag: true
        noModelComment: true
        stdTime: true
        typeMapping:
          timestamp:
            type: "*time.Time"
            import: time
          "timestamp without time zone":
            type: "*time.Time"
            import: time
          timestamptz:
            type: "*time.Time"
            import: time
          "timestamp with time zone":
            type: "*time.Time"
            import: time
