-- PostgreSQL translation of the legacy uidentity/admin MySQL schema.
-- Data is global in this plugin; legacy tenant-scoped columns are intentionally absent.

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(32) NOT NULL DEFAULT '',
    name VARCHAR(32) NOT NULL DEFAULT '',
    phone VARCHAR(16) NOT NULL DEFAULT '',
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    group_id BIGINT NULL,
    pass_level SMALLINT NOT NULL DEFAULT 0,
    container_id BIGINT NULL,
    unit_id BIGINT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_number ON plugin_linapro_uidentity_cas_account (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_phone ON plugin_linapro_uidentity_cas_account (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_name ON plugin_linapro_uidentity_cas_account (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_deleted_at ON plugin_linapro_uidentity_cas_account (deleted_at);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_status ON plugin_linapro_uidentity_cas_account (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_container ON plugin_linapro_uidentity_cas_account (container_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit ON plugin_linapro_uidentity_cas_account (unit_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_details (
    account_id BIGINT PRIMARY KEY,
    birthday TIMESTAMP NULL,
    email VARCHAR(64) NOT NULL DEFAULT '',
    gender SMALLINT NOT NULL DEFAULT 0,
    qq VARCHAR(16) NOT NULL DEFAULT '',
    wechat VARCHAR(64) NOT NULL DEFAULT '',
    idcard VARCHAR(32) NOT NULL DEFAULT '',
    avatar VARCHAR(255) NOT NULL DEFAULT '',
    source VARCHAR(16) NOT NULL DEFAULT '',
    nj VARCHAR(16) NOT NULL DEFAULT '',
    xymc VARCHAR(128) NOT NULL DEFAULT '',
    xydm VARCHAR(32) NOT NULL DEFAULT '',
    xq VARCHAR(128) NOT NULL DEFAULT '',
    xz VARCHAR(32) NOT NULL DEFAULT '',
    yjbysj VARCHAR(32) NOT NULL DEFAULT '',
    zymc VARCHAR(128) NOT NULL DEFAULT '',
    bjmc VARCHAR(128) NOT NULL DEFAULT '',
    face BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_email ON plugin_linapro_uidentity_cas_account_details (email);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_source ON plugin_linapro_uidentity_cas_account_details (source);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_deleted_at ON plugin_linapro_uidentity_cas_account_details (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT '',
    alias VARCHAR(255) NOT NULL DEFAULT '',
    account_count BIGINT NOT NULL DEFAULT 0,
    admin_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_name ON plugin_linapro_uidentity_cas_containers (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_deleted_at ON plugin_linapro_uidentity_cas_containers (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT '',
    alias VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_name ON plugin_linapro_uidentity_cas_groups (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_deleted_at ON plugin_linapro_uidentity_cas_groups (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT '',
    alias VARCHAR(255) NOT NULL DEFAULT '',
    code BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_name ON plugin_linapro_uidentity_cas_units (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_code ON plugin_linapro_uidentity_cas_units (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_deleted_at ON plugin_linapro_uidentity_cas_units (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT '',
    alias VARCHAR(255) NOT NULL DEFAULT '',
    client_id VARCHAR(32) NOT NULL DEFAULT '',
    secret_key VARCHAR(32) NOT NULL DEFAULT '',
    access_model TEXT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    callback_url VARCHAR(255) NOT NULL DEFAULT '',
    whitelist TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_name ON plugin_linapro_uidentity_cas_applications (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_client_id ON plugin_linapro_uidentity_cas_applications (client_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_status ON plugin_linapro_uidentity_cas_applications (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_deleted_at ON plugin_linapro_uidentity_cas_applications (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_group (
    account_id BIGINT NOT NULL,
    groups_id BIGINT NOT NULL,
    PRIMARY KEY (account_id, groups_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_group_groups_id ON plugin_linapro_uidentity_cas_account_group (groups_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL DEFAULT 0,
    units_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_account_id ON plugin_linapro_uidentity_cas_account_unit (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_units_id ON plugin_linapro_uidentity_cas_account_unit (units_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_deleted_at ON plugin_linapro_uidentity_cas_account_unit (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    give_account_id BIGINT NOT NULL DEFAULT 0,
    empowered_account_id BIGINT NOT NULL DEFAULT 0,
    app_id BIGINT NOT NULL DEFAULT 0,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_give_account ON plugin_linapro_uidentity_cas_account_app_role (give_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_empowered_account ON plugin_linapro_uidentity_cas_account_app_role (empowered_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_app_id ON plugin_linapro_uidentity_cas_account_app_role (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_deleted_at ON plugin_linapro_uidentity_cas_account_app_role (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    app_id BIGINT NOT NULL DEFAULT 0,
    account_id BIGINT NOT NULL DEFAULT 0,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_app_id ON plugin_linapro_uidentity_cas_account_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_account_id ON plugin_linapro_uidentity_cas_account_app_blacklist (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_account_app_blacklist (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_group_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    app_id BIGINT NOT NULL DEFAULT 0,
    group_id BIGINT NOT NULL DEFAULT 0,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_app_id ON plugin_linapro_uidentity_cas_group_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_group_id ON plugin_linapro_uidentity_cas_group_app_blacklist (group_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_group_app_blacklist (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_pass_ruler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT '',
    capital BIGINT NOT NULL DEFAULT 0,
    lower BIGINT NOT NULL DEFAULT 0,
    number BIGINT NOT NULL DEFAULT 0,
    symbol BIGINT NOT NULL DEFAULT 0,
    length BIGINT NOT NULL DEFAULT 0,
    "interval" BIGINT NOT NULL DEFAULT 0,
    interval_status SMALLINT NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_name ON plugin_linapro_uidentity_cas_pass_ruler (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_status ON plugin_linapro_uidentity_cas_pass_ruler (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_deleted_at ON plugin_linapro_uidentity_cas_pass_ruler (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(16) NOT NULL DEFAULT '',
    type VARCHAR(16) NOT NULL DEFAULT '',
    content VARCHAR(255) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 0,
    resp_msg TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_phone ON plugin_linapro_uidentity_cas_sms (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_type ON plugin_linapro_uidentity_cas_sms (type);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_deleted_at ON plugin_linapro_uidentity_cas_sms (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_cas_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL DEFAULT 0,
    choice_account_id BIGINT NOT NULL DEFAULT 0,
    app_id BIGINT NOT NULL DEFAULT 0,
    ipaddr VARCHAR(128) NOT NULL DEFAULT '',
    login_location VARCHAR(255) NOT NULL DEFAULT '',
    browser VARCHAR(64) NOT NULL DEFAULT '',
    os VARCHAR(64) NOT NULL DEFAULT '',
    platform VARCHAR(64) NOT NULL DEFAULT '',
    login_time TIMESTAMP NULL,
    remark VARCHAR(255) NOT NULL DEFAULT '',
    msg VARCHAR(255) NOT NULL DEFAULT '',
    login_type VARCHAR(32) NOT NULL DEFAULT '',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_account_id ON plugin_linapro_uidentity_cas_cas_login_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_app_id ON plugin_linapro_uidentity_cas_cas_login_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_login_time ON plugin_linapro_uidentity_cas_cas_login_log (login_time);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_deleted_at ON plugin_linapro_uidentity_cas_cas_login_log (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 0,
    app_id BIGINT NOT NULL DEFAULT 0,
    redirect_uri VARCHAR(255) NOT NULL DEFAULT '',
    scope VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_user_id ON plugin_linapro_uidentity_cas_oauth_log (user_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_app_id ON plugin_linapro_uidentity_cas_oauth_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_deleted_at ON plugin_linapro_uidentity_cas_oauth_log (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth2_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expired_at BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(255) NOT NULL DEFAULT '',
    access VARCHAR(255) NOT NULL DEFAULT '',
    refresh VARCHAR(255) NOT NULL DEFAULT '',
    data TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_code ON plugin_linapro_uidentity_cas_oauth2_token (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_access ON plugin_linapro_uidentity_cas_oauth2_token (access);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_refresh ON plugin_linapro_uidentity_cas_oauth2_token (refresh);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_expired_at ON plugin_linapro_uidentity_cas_oauth2_token (expired_at);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_deleted_at ON plugin_linapro_uidentity_cas_oauth2_token (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL DEFAULT 0,
    table_name VARCHAR(64) NOT NULL DEFAULT '',
    action VARCHAR(64) NOT NULL DEFAULT '',
    data_old TEXT NULL,
    data_new TEXT NULL,
    err_msg TEXT NULL,
    err_number SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_account_id ON plugin_linapro_uidentity_cas_account_change_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_table_name ON plugin_linapro_uidentity_cas_account_change_log (table_name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_deleted_at ON plugin_linapro_uidentity_cas_account_change_log (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_active_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(32) NOT NULL DEFAULT '',
    phone VARCHAR(16) NOT NULL DEFAULT '',
    wechat VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP NULL,
    type BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_number ON plugin_linapro_uidentity_cas_account_active_log (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_phone ON plugin_linapro_uidentity_cas_account_active_log (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_type ON plugin_linapro_uidentity_cas_account_active_log (type);

INSERT INTO plugin_linapro_uidentity_cas_pass_ruler (
    name, capital, lower, number, symbol, length, "interval", interval_status, status, created_at, updated_at
)
SELECT 'default', 0, 0, 1, 0, 8, 90, 1, 1, NOW(), NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM plugin_linapro_uidentity_cas_pass_ruler WHERE name = 'default' AND deleted_at IS NULL
);
