-- PostgreSQL translation of the legacy uidentity/admin MySQL schema.
-- Data is global in this plugin; legacy tenant-scoped columns are intentionally absent.

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(128) NULL,
    name VARCHAR(128) NULL,
    phone VARCHAR(128) NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    group_id BIGINT NULL,
    pass_level BIGINT NULL,
    container_id BIGINT NULL,
    unit_id BIGINT NULL,
    status BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_number ON plugin_linapro_uidentity_cas_account (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_phone ON plugin_linapro_uidentity_cas_account (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_name ON plugin_linapro_uidentity_cas_account (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_deleted_at ON plugin_linapro_uidentity_cas_account (deleted_at);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_status ON plugin_linapro_uidentity_cas_account (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_container ON plugin_linapro_uidentity_cas_account (container_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit ON plugin_linapro_uidentity_cas_account (unit_id);

ALTER TABLE plugin_linapro_uidentity_cas_account
    ALTER COLUMN number TYPE VARCHAR(128),
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN pass_level TYPE BIGINT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN pass_level DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN pass_level DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_details (
    account_id BIGINT PRIMARY KEY,
    birthday TIMESTAMP NULL,
    email VARCHAR(128) NULL,
    gender BIGINT NULL,
    qq VARCHAR(128) NULL,
    wechat VARCHAR(128) NULL,
    idcard VARCHAR(128) NULL,
    avatar VARCHAR(128) NULL,
    source VARCHAR(128) NULL,
    nj BIGINT NULL,
    xymc VARCHAR(255) NULL,
    xydm VARCHAR(255) NULL,
    xq VARCHAR(255) NULL,
    xz BIGINT NULL,
    yjbysj BIGINT NULL,
    zymc VARCHAR(255) NULL,
    bjmc VARCHAR(255) NULL,
    face BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_email ON plugin_linapro_uidentity_cas_account_details (email);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_source ON plugin_linapro_uidentity_cas_account_details (source);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_deleted_at ON plugin_linapro_uidentity_cas_account_details (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_details
    ALTER COLUMN gender DROP DEFAULT,
    ALTER COLUMN nj DROP DEFAULT,
    ALTER COLUMN xz DROP DEFAULT,
    ALTER COLUMN yjbysj DROP DEFAULT,
    ALTER COLUMN face DROP DEFAULT;

ALTER TABLE plugin_linapro_uidentity_cas_account_details
    ALTER COLUMN email TYPE VARCHAR(128),
    ALTER COLUMN gender TYPE BIGINT,
    ALTER COLUMN qq TYPE VARCHAR(128),
    ALTER COLUMN wechat TYPE VARCHAR(128),
    ALTER COLUMN idcard TYPE VARCHAR(128),
    ALTER COLUMN avatar TYPE VARCHAR(128),
    ALTER COLUMN source TYPE VARCHAR(128),
    ALTER COLUMN nj TYPE BIGINT USING CASE WHEN nj::text ~ '^-?[0-9]+$' THEN nj::text::bigint ELSE NULL END,
    ALTER COLUMN xymc TYPE VARCHAR(255),
    ALTER COLUMN xydm TYPE VARCHAR(255),
    ALTER COLUMN xq TYPE VARCHAR(255),
    ALTER COLUMN xz TYPE BIGINT USING CASE WHEN xz::text ~ '^-?[0-9]+$' THEN xz::text::bigint ELSE NULL END,
    ALTER COLUMN yjbysj TYPE BIGINT USING CASE WHEN yjbysj::text ~ '^-?[0-9]+$' THEN yjbysj::text::bigint ELSE NULL END,
    ALTER COLUMN zymc TYPE VARCHAR(255),
    ALTER COLUMN bjmc TYPE VARCHAR(255),
    ALTER COLUMN face TYPE BIGINT USING CASE WHEN face::text ~ '^-?[0-9]+$' THEN face::text::bigint ELSE NULL END,
    ALTER COLUMN email DROP NOT NULL,
    ALTER COLUMN gender DROP NOT NULL,
    ALTER COLUMN qq DROP NOT NULL,
    ALTER COLUMN wechat DROP NOT NULL,
    ALTER COLUMN idcard DROP NOT NULL,
    ALTER COLUMN avatar DROP NOT NULL,
    ALTER COLUMN source DROP NOT NULL,
    ALTER COLUMN nj DROP NOT NULL,
    ALTER COLUMN xymc DROP NOT NULL,
    ALTER COLUMN xydm DROP NOT NULL,
    ALTER COLUMN xq DROP NOT NULL,
    ALTER COLUMN xz DROP NOT NULL,
    ALTER COLUMN yjbysj DROP NOT NULL,
    ALTER COLUMN zymc DROP NOT NULL,
    ALTER COLUMN bjmc DROP NOT NULL,
    ALTER COLUMN face DROP NOT NULL,
    ALTER COLUMN email DROP DEFAULT,
    ALTER COLUMN gender DROP DEFAULT,
    ALTER COLUMN qq DROP DEFAULT,
    ALTER COLUMN wechat DROP DEFAULT,
    ALTER COLUMN idcard DROP DEFAULT,
    ALTER COLUMN avatar DROP DEFAULT,
    ALTER COLUMN source DROP DEFAULT,
    ALTER COLUMN nj DROP DEFAULT,
    ALTER COLUMN xymc DROP DEFAULT,
    ALTER COLUMN xydm DROP DEFAULT,
    ALTER COLUMN xq DROP DEFAULT,
    ALTER COLUMN xz DROP DEFAULT,
    ALTER COLUMN yjbysj DROP DEFAULT,
    ALTER COLUMN zymc DROP DEFAULT,
    ALTER COLUMN bjmc DROP DEFAULT,
    ALTER COLUMN face DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    account_count BIGINT NULL,
    admin_count BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_name ON plugin_linapro_uidentity_cas_containers (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_deleted_at ON plugin_linapro_uidentity_cas_containers (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_containers
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN account_count DROP NOT NULL,
    ALTER COLUMN admin_count DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN account_count DROP DEFAULT,
    ALTER COLUMN admin_count DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_name ON plugin_linapro_uidentity_cas_groups (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_deleted_at ON plugin_linapro_uidentity_cas_groups (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_groups
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    code BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_name ON plugin_linapro_uidentity_cas_units (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_code ON plugin_linapro_uidentity_cas_units (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_deleted_at ON plugin_linapro_uidentity_cas_units (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_units
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN code DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN code DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    client_id VARCHAR(128) NULL,
    secret_key VARCHAR(128) NULL,
    access_model VARCHAR(128) NULL,
    status BIGINT NULL,
    callback_url VARCHAR(128) NULL,
    whitelist TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_name ON plugin_linapro_uidentity_cas_applications (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_client_id ON plugin_linapro_uidentity_cas_applications (client_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_status ON plugin_linapro_uidentity_cas_applications (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_deleted_at ON plugin_linapro_uidentity_cas_applications (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_applications
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN client_id TYPE VARCHAR(128),
    ALTER COLUMN secret_key TYPE VARCHAR(128),
    ALTER COLUMN access_model TYPE VARCHAR(128),
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN callback_url TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN client_id DROP NOT NULL,
    ALTER COLUMN secret_key DROP NOT NULL,
    ALTER COLUMN access_model DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN callback_url DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN client_id DROP DEFAULT,
    ALTER COLUMN secret_key DROP DEFAULT,
    ALTER COLUMN access_model DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT,
    ALTER COLUMN callback_url DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_group (
    account_id BIGINT NOT NULL,
    groups_id BIGINT NOT NULL,
    PRIMARY KEY (account_id, groups_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_group_groups_id ON plugin_linapro_uidentity_cas_account_group (groups_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'plugin_linapro_uidentity_cas_account_unit'
          AND column_name = 'units_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'plugin_linapro_uidentity_cas_account_unit'
          AND column_name = 'unit_id'
    ) THEN
        ALTER TABLE plugin_linapro_uidentity_cas_account_unit RENAME COLUMN units_id TO unit_id;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_account_id ON plugin_linapro_uidentity_cas_account_unit (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_unit_id ON plugin_linapro_uidentity_cas_account_unit (unit_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_unique ON plugin_linapro_uidentity_cas_account_unit (account_id, unit_id);

ALTER TABLE plugin_linapro_uidentity_cas_account_unit
    ALTER COLUMN account_id TYPE BIGINT,
    ALTER COLUMN unit_id TYPE BIGINT,
    ALTER COLUMN account_id SET NOT NULL,
    ALTER COLUMN unit_id SET NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN unit_id DROP DEFAULT;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS units_id;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS created_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS updated_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS create_by;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS update_by;
DROP INDEX IF EXISTS idx_uidentity_cas_account_unit_units_id;
DROP INDEX IF EXISTS idx_uidentity_cas_account_unit_deleted_at;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    give_account_id BIGINT NULL,
    empowered_account_id BIGINT NULL,
    app_id BIGINT NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_give_account ON plugin_linapro_uidentity_cas_account_app_role (give_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_empowered_account ON plugin_linapro_uidentity_cas_account_app_role (empowered_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_app_id ON plugin_linapro_uidentity_cas_account_app_role (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_deleted_at ON plugin_linapro_uidentity_cas_account_app_role (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_app_role
    ALTER COLUMN give_account_id DROP NOT NULL,
    ALTER COLUMN empowered_account_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN give_account_id DROP DEFAULT,
    ALTER COLUMN empowered_account_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    app_id BIGINT NULL,
    account_id BIGINT NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_app_id ON plugin_linapro_uidentity_cas_account_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_account_id ON plugin_linapro_uidentity_cas_account_app_blacklist (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_account_app_blacklist (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_app_blacklist
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN account_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_group_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    app_id BIGINT NULL,
    group_id BIGINT NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_app_id ON plugin_linapro_uidentity_cas_group_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_group_id ON plugin_linapro_uidentity_cas_group_app_blacklist (group_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_group_app_blacklist (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_group_app_blacklist
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN group_id DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN group_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_pass_ruler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    capital BIGINT NULL,
    lower BIGINT NULL,
    number BIGINT NULL,
    symbol BIGINT NULL,
    length BIGINT NULL,
    "interval" BIGINT NULL,
    interval_status BIGINT NULL,
    status BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_name ON plugin_linapro_uidentity_cas_pass_ruler (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_status ON plugin_linapro_uidentity_cas_pass_ruler (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_deleted_at ON plugin_linapro_uidentity_cas_pass_ruler (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_pass_ruler
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN interval_status TYPE BIGINT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN capital DROP NOT NULL,
    ALTER COLUMN lower DROP NOT NULL,
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN symbol DROP NOT NULL,
    ALTER COLUMN length DROP NOT NULL,
    ALTER COLUMN "interval" DROP NOT NULL,
    ALTER COLUMN interval_status DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN capital DROP DEFAULT,
    ALTER COLUMN lower DROP DEFAULT,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN symbol DROP DEFAULT,
    ALTER COLUMN length DROP DEFAULT,
    ALTER COLUMN "interval" DROP DEFAULT,
    ALTER COLUMN interval_status DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(128) NULL,
    type VARCHAR(128) NULL,
    content TEXT NULL,
    status BIGINT NULL,
    resp_msg TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_phone ON plugin_linapro_uidentity_cas_sms (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_type ON plugin_linapro_uidentity_cas_sms (type);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_deleted_at ON plugin_linapro_uidentity_cas_sms (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_sms
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN type TYPE VARCHAR(128),
    ALTER COLUMN content TYPE TEXT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN type DROP NOT NULL,
    ALTER COLUMN content DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN type DROP DEFAULT,
    ALTER COLUMN content DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_cas_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NULL,
    choice_account_id BIGINT NULL,
    app_id BIGINT NULL,
    ipaddr VARCHAR(255) NULL,
    login_location VARCHAR(255) NULL,
    browser VARCHAR(255) NULL,
    os VARCHAR(255) NULL,
    platform VARCHAR(255) NULL,
    login_time TIMESTAMP NULL,
    remark VARCHAR(255) NULL,
    msg VARCHAR(255) NULL,
    login_type VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_account_id ON plugin_linapro_uidentity_cas_cas_login_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_app_id ON plugin_linapro_uidentity_cas_cas_login_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_login_time ON plugin_linapro_uidentity_cas_cas_login_log (login_time);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_deleted_at ON plugin_linapro_uidentity_cas_cas_login_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_cas_login_log
    ALTER COLUMN ipaddr TYPE VARCHAR(255),
    ALTER COLUMN browser TYPE VARCHAR(255),
    ALTER COLUMN os TYPE VARCHAR(255),
    ALTER COLUMN platform TYPE VARCHAR(255),
    ALTER COLUMN login_type TYPE VARCHAR(255),
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN choice_account_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN ipaddr DROP NOT NULL,
    ALTER COLUMN login_location DROP NOT NULL,
    ALTER COLUMN browser DROP NOT NULL,
    ALTER COLUMN os DROP NOT NULL,
    ALTER COLUMN platform DROP NOT NULL,
    ALTER COLUMN remark DROP NOT NULL,
    ALTER COLUMN msg DROP NOT NULL,
    ALTER COLUMN login_type DROP NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN choice_account_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN ipaddr DROP DEFAULT,
    ALTER COLUMN login_location DROP DEFAULT,
    ALTER COLUMN browser DROP DEFAULT,
    ALTER COLUMN os DROP DEFAULT,
    ALTER COLUMN platform DROP DEFAULT,
    ALTER COLUMN remark DROP DEFAULT,
    ALTER COLUMN msg DROP DEFAULT,
    ALTER COLUMN login_type DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    app_id BIGINT NULL,
    redirect_uri VARCHAR(256) NULL,
    scope VARCHAR(256) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_user_id ON plugin_linapro_uidentity_cas_oauth_log (user_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_app_id ON plugin_linapro_uidentity_cas_oauth_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_deleted_at ON plugin_linapro_uidentity_cas_oauth_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_oauth_log
    ALTER COLUMN redirect_uri TYPE VARCHAR(256),
    ALTER COLUMN scope TYPE VARCHAR(256),
    ALTER COLUMN user_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN redirect_uri DROP NOT NULL,
    ALTER COLUMN scope DROP NOT NULL,
    ALTER COLUMN user_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN redirect_uri DROP DEFAULT,
    ALTER COLUMN scope DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth2_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expired_at BIGINT NULL,
    code TEXT NULL,
    access TEXT NULL,
    refresh TEXT NULL,
    data TEXT NULL
);

ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS created_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS updated_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS create_by;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS update_by;

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_code ON plugin_linapro_uidentity_cas_oauth2_token (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_access ON plugin_linapro_uidentity_cas_oauth2_token (access);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_refresh ON plugin_linapro_uidentity_cas_oauth2_token (refresh);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_expired_at ON plugin_linapro_uidentity_cas_oauth2_token (expired_at);
DROP INDEX IF EXISTS idx_uidentity_cas_oauth2_token_deleted_at;

ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token
    ALTER COLUMN code TYPE TEXT,
    ALTER COLUMN access TYPE TEXT,
    ALTER COLUMN refresh TYPE TEXT,
    ALTER COLUMN expired_at DROP NOT NULL,
    ALTER COLUMN code DROP NOT NULL,
    ALTER COLUMN access DROP NOT NULL,
    ALTER COLUMN refresh DROP NOT NULL,
    ALTER COLUMN expired_at DROP DEFAULT,
    ALTER COLUMN code DROP DEFAULT,
    ALTER COLUMN access DROP DEFAULT,
    ALTER COLUMN refresh DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NULL,
    table_name VARCHAR(128) NULL,
    action VARCHAR(128) NULL,
    data_old TEXT NULL,
    data_new TEXT NULL,
    err_msg TEXT NULL,
    err_number TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_account_id ON plugin_linapro_uidentity_cas_account_change_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_table_name ON plugin_linapro_uidentity_cas_account_change_log (table_name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_deleted_at ON plugin_linapro_uidentity_cas_account_change_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_change_log
    ALTER COLUMN table_name TYPE VARCHAR(128),
    ALTER COLUMN action TYPE VARCHAR(128),
    ALTER COLUMN err_number TYPE TEXT USING err_number::text,
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN table_name DROP NOT NULL,
    ALTER COLUMN action DROP NOT NULL,
    ALTER COLUMN err_number DROP NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN table_name DROP DEFAULT,
    ALTER COLUMN action DROP DEFAULT,
    ALTER COLUMN err_number DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_active_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(128) NULL,
    phone VARCHAR(128) NULL,
    wechat VARCHAR(128) NULL,
    created_at TIMESTAMP NULL,
    type BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_number ON plugin_linapro_uidentity_cas_account_active_log (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_phone ON plugin_linapro_uidentity_cas_account_active_log (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_type ON plugin_linapro_uidentity_cas_account_active_log (type);

ALTER TABLE plugin_linapro_uidentity_cas_account_active_log
    ALTER COLUMN number TYPE VARCHAR(128),
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN wechat TYPE VARCHAR(128),
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN wechat DROP NOT NULL,
    ALTER COLUMN type DROP NOT NULL,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN wechat DROP DEFAULT,
    ALTER COLUMN type DROP DEFAULT;

-- Legacy GoAdmin system-management compatibility tables. They are prefixed for
-- plugin ownership, while the table suffixes and columns keep the old project
-- contract. Scheduler execution still uses GF/host jobs; sys_job/job_log are
-- schema compatibility tables only.

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_dept (
    dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NULL,
    dept_path VARCHAR(255) NULL,
    dept_name VARCHAR(128) NULL,
    sort BIGINT NULL,
    leader VARCHAR(128) NULL,
    phone VARCHAR(11) NULL,
    email VARCHAR(64) NULL,
    status BIGINT NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dept_parent_id ON plugin_linapro_uidentity_cas_sys_dept (parent_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dept_path ON plugin_linapro_uidentity_cas_sys_dept (dept_path);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dept_status ON plugin_linapro_uidentity_cas_sys_dept (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dept_deleted_at ON plugin_linapro_uidentity_cas_sys_dept (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(128) NULL,
    config_key VARCHAR(128) NULL,
    config_value VARCHAR(255) NULL,
    config_type VARCHAR(64) NULL,
    is_frontend VARCHAR(64) NULL,
    remark VARCHAR(128) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_config_key ON plugin_linapro_uidentity_cas_sys_config (config_key);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_config_frontend ON plugin_linapro_uidentity_cas_sys_config (is_frontend);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_config_deleted_at ON plugin_linapro_uidentity_cas_sys_config (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_tables (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(255) NULL,
    table_comment VARCHAR(255) NULL,
    class_name VARCHAR(255) NULL,
    tpl_category VARCHAR(255) NULL,
    package_name VARCHAR(255) NULL,
    module_name VARCHAR(255) NULL,
    module_front_name VARCHAR(255) NULL,
    business_name VARCHAR(255) NULL,
    function_name VARCHAR(255) NULL,
    function_author VARCHAR(255) NULL,
    pk_column VARCHAR(255) NULL,
    pk_go_field VARCHAR(255) NULL,
    pk_json_field VARCHAR(255) NULL,
    options VARCHAR(255) NULL,
    tree_code VARCHAR(255) NULL,
    tree_parent_code VARCHAR(255) NULL,
    tree_name VARCHAR(255) NULL,
    tree BOOLEAN NULL,
    crud BOOLEAN NULL,
    remark VARCHAR(255) NULL,
    is_data_scope BIGINT NULL,
    is_actions BIGINT NULL,
    is_auth BIGINT NULL,
    is_logical_delete VARCHAR(1) NULL,
    logical_delete BOOLEAN NULL,
    logical_delete_column VARCHAR(128) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_tables_table_name ON plugin_linapro_uidentity_cas_sys_tables (table_name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_tables_deleted_at ON plugin_linapro_uidentity_cas_sys_tables (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_columns (
    column_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NULL,
    column_name VARCHAR(128) NULL,
    column_comment VARCHAR(128) NULL,
    column_type VARCHAR(128) NULL,
    go_type VARCHAR(128) NULL,
    go_field VARCHAR(128) NULL,
    json_field VARCHAR(128) NULL,
    is_pk VARCHAR(4) NULL,
    is_increment VARCHAR(4) NULL,
    is_required VARCHAR(4) NULL,
    is_insert VARCHAR(4) NULL,
    is_edit VARCHAR(4) NULL,
    is_list VARCHAR(4) NULL,
    is_query VARCHAR(4) NULL,
    query_type VARCHAR(128) NULL,
    html_type VARCHAR(128) NULL,
    dict_type VARCHAR(128) NULL,
    sort BIGINT NULL,
    list VARCHAR(1) NULL,
    pk BOOLEAN NULL,
    required BOOLEAN NULL,
    super_column BOOLEAN NULL,
    usable_column BOOLEAN NULL,
    increment BOOLEAN NULL,
    insert BOOLEAN NULL,
    edit BOOLEAN NULL,
    query BOOLEAN NULL,
    remark VARCHAR(255) NULL,
    fk_table_name VARCHAR(255) NULL,
    fk_table_name_class VARCHAR(255) NULL,
    fk_table_name_package VARCHAR(255) NULL,
    fk_label_id VARCHAR(255) NULL,
    fk_label_name VARCHAR(255) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_columns_table_id ON plugin_linapro_uidentity_cas_sys_columns (table_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_columns_deleted_at ON plugin_linapro_uidentity_cas_sys_columns (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_menu (
    menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name VARCHAR(128) NULL,
    title VARCHAR(128) NULL,
    icon VARCHAR(128) NULL,
    path VARCHAR(128) NULL,
    paths VARCHAR(128) NULL,
    menu_type VARCHAR(1) NULL,
    action VARCHAR(16) NULL,
    permission VARCHAR(255) NULL,
    parent_id BIGINT NULL,
    no_cache BOOLEAN NULL,
    breadcrumb VARCHAR(255) NULL,
    component VARCHAR(255) NULL,
    sort BIGINT NULL,
    visible VARCHAR(1) NULL,
    is_frame VARCHAR(1) NULL DEFAULT '0',
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_menu_parent_id ON plugin_linapro_uidentity_cas_sys_menu (parent_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_menu_permission ON plugin_linapro_uidentity_cas_sys_menu (permission);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_menu_deleted_at ON plugin_linapro_uidentity_cas_sys_menu (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NULL,
    status VARCHAR(4) NULL,
    ipaddr VARCHAR(255) NULL,
    login_location VARCHAR(255) NULL,
    browser VARCHAR(255) NULL,
    os VARCHAR(255) NULL,
    platform VARCHAR(255) NULL,
    login_time TIMESTAMP NULL,
    remark VARCHAR(255) NULL,
    msg VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_login_log_username ON plugin_linapro_uidentity_cas_sys_login_log (username);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_login_log_status ON plugin_linapro_uidentity_cas_sys_login_log (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_login_log_login_time ON plugin_linapro_uidentity_cas_sys_login_log (login_time);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_opera_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NULL,
    business_type VARCHAR(128) NULL,
    business_types VARCHAR(128) NULL,
    method VARCHAR(128) NULL,
    request_method VARCHAR(128) NULL,
    operator_type VARCHAR(128) NULL,
    oper_name VARCHAR(128) NULL,
    dept_name VARCHAR(128) NULL,
    oper_url VARCHAR(255) NULL,
    oper_ip VARCHAR(128) NULL,
    oper_location VARCHAR(128) NULL,
    oper_param TEXT NULL,
    status VARCHAR(4) NULL,
    oper_time TIMESTAMP NULL,
    json_result VARCHAR(255) NULL,
    remark VARCHAR(255) NULL,
    latency_time VARCHAR(128) NULL,
    user_agent VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_opera_log_title ON plugin_linapro_uidentity_cas_sys_opera_log (title);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_opera_log_oper_ip ON plugin_linapro_uidentity_cas_sys_opera_log (oper_ip);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_opera_log_created_at ON plugin_linapro_uidentity_cas_sys_opera_log (created_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_role_dept (
    role_id BIGINT NOT NULL,
    dept_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, dept_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_role_dept_dept_id ON plugin_linapro_uidentity_cas_sys_role_dept (dept_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NULL,
    password VARCHAR(128) NULL,
    nick_name VARCHAR(128) NULL,
    phone VARCHAR(11) NULL,
    role_id BIGINT NULL,
    salt VARCHAR(255) NULL,
    avatar VARCHAR(255) NULL,
    sex VARCHAR(255) NULL,
    email VARCHAR(128) NULL,
    dept_id BIGINT NULL,
    post_id BIGINT NULL,
    remark VARCHAR(255) NULL,
    status VARCHAR(4) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_user_username ON plugin_linapro_uidentity_cas_sys_user (username);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_user_phone ON plugin_linapro_uidentity_cas_sys_user (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_user_dept_id ON plugin_linapro_uidentity_cas_sys_user (dept_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_user_deleted_at ON plugin_linapro_uidentity_cas_sys_user (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(128) NULL,
    status VARCHAR(4) NULL,
    role_key VARCHAR(128) NULL,
    role_sort BIGINT NULL,
    flag VARCHAR(128) NULL,
    remark VARCHAR(255) NULL,
    admin BOOLEAN NULL,
    data_scope VARCHAR(128) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_role_key ON plugin_linapro_uidentity_cas_sys_role (role_key);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_role_status ON plugin_linapro_uidentity_cas_sys_role (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_role_deleted_at ON plugin_linapro_uidentity_cas_sys_role (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_role_menu_menu_id ON plugin_linapro_uidentity_cas_sys_role_menu (menu_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_post (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_name VARCHAR(128) NULL,
    post_code VARCHAR(128) NULL,
    sort BIGINT NULL,
    status BIGINT NULL,
    remark VARCHAR(255) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_post_code ON plugin_linapro_uidentity_cas_sys_post (post_code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_post_status ON plugin_linapro_uidentity_cas_sys_post (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_post_deleted_at ON plugin_linapro_uidentity_cas_sys_post (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_dict_data (
    dict_code BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_sort BIGINT NULL,
    dict_label VARCHAR(128) NULL,
    dict_value VARCHAR(255) NULL,
    dict_type VARCHAR(64) NULL,
    css_class VARCHAR(128) NULL,
    list_class VARCHAR(128) NULL,
    is_default VARCHAR(8) NULL,
    status BIGINT NULL,
    "default" VARCHAR(8) NULL,
    remark VARCHAR(255) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_data_type ON plugin_linapro_uidentity_cas_sys_dict_data (dict_type);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_data_status ON plugin_linapro_uidentity_cas_sys_dict_data (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_data_deleted_at ON plugin_linapro_uidentity_cas_sys_dict_data (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_dict_type (
    dict_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name VARCHAR(128) NULL,
    dict_type VARCHAR(128) NULL,
    status BIGINT NULL,
    remark VARCHAR(255) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_type_type ON plugin_linapro_uidentity_cas_sys_dict_type (dict_type);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_type_status ON plugin_linapro_uidentity_cas_sys_dict_type (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_dict_type_deleted_at ON plugin_linapro_uidentity_cas_sys_dict_type (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_api (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle VARCHAR(128) NULL,
    title VARCHAR(128) NULL,
    path VARCHAR(128) NULL,
    type VARCHAR(16) NULL,
    action VARCHAR(16) NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_api_path_action ON plugin_linapro_uidentity_cas_sys_api (path, action);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_api_deleted_at ON plugin_linapro_uidentity_cas_sys_api (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_menu_api_rule (
    sys_menu_menu_id BIGINT NOT NULL,
    sys_api_id BIGINT NOT NULL,
    PRIMARY KEY (sys_menu_menu_id, sys_api_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_menu_api_rule_api_id ON plugin_linapro_uidentity_cas_sys_menu_api_rule (sys_api_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(255) NULL,
    job_group VARCHAR(255) NULL,
    job_type BIGINT NULL,
    cron_expression VARCHAR(255) NULL,
    invoke_target VARCHAR(255) NULL,
    args VARCHAR(255) NULL,
    misfire_policy BIGINT NULL,
    concurrent BIGINT NULL,
    status BIGINT NULL,
    entry_id BIGINT NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_job_status ON plugin_linapro_uidentity_cas_sys_job (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sys_job_deleted_at ON plugin_linapro_uidentity_cas_sys_job (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_job_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NULL,
    job_name VARCHAR(128) NULL,
    start_at TIMESTAMP NULL,
    end_at TIMESTAMP NULL,
    create_num BIGINT NULL,
    update_num BIGINT NULL,
    delete_num BIGINT NULL,
    err_num BIGINT NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_job_log_job_id ON plugin_linapro_uidentity_cas_job_log (job_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_job_log_start_at ON plugin_linapro_uidentity_cas_job_log (start_at);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_job_log_deleted_at ON plugin_linapro_uidentity_cas_job_log (deleted_at);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sys_casbin_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype VARCHAR(512) NULL,
    v0 VARCHAR(512) NULL,
    v1 VARCHAR(512) NULL,
    v2 VARCHAR(512) NULL,
    v3 VARCHAR(512) NULL,
    v4 VARCHAR(512) NULL,
    v5 VARCHAR(512) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uidentity_cas_sys_casbin_rule_unique
    ON plugin_linapro_uidentity_cas_sys_casbin_rule (
        COALESCE(ptype, ''),
        COALESCE(v0, ''),
        COALESCE(v1, ''),
        COALESCE(v2, ''),
        COALESCE(v3, ''),
        COALESCE(v4, ''),
        COALESCE(v5, '')
    );

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_tb_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_tb_demo_name ON plugin_linapro_uidentity_cas_tb_demo (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_tb_demo_deleted_at ON plugin_linapro_uidentity_cas_tb_demo (deleted_at);

INSERT INTO plugin_linapro_uidentity_cas_pass_ruler (
    name, capital, lower, number, symbol, length, "interval", interval_status, status, created_at, updated_at
)
SELECT 'default', 0, 0, 1, 0, 8, 90, 1, 1, NOW(), NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM plugin_linapro_uidentity_cas_pass_ruler WHERE name = 'default' AND deleted_at IS NULL
);
