-- PostgreSQL translation of the legacy uidentity/admin MySQL schema.
-- Data is global in this plugin; legacy tenant-scoped columns are intentionally absent.

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(128) NULL,
    name VARCHAR(128) NULL,
    phone VARCHAR(128) NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    group_id BIGINT NULL,
    pass_level BIGINT NULL,
    container_id BIGINT NULL,
    unit_id BIGINT NULL,
    status BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_number ON plugin_linapro_uidentity_cas_account (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_phone ON plugin_linapro_uidentity_cas_account (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_name ON plugin_linapro_uidentity_cas_account (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_deleted_at ON plugin_linapro_uidentity_cas_account (deleted_at);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_status ON plugin_linapro_uidentity_cas_account (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_container ON plugin_linapro_uidentity_cas_account (container_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit ON plugin_linapro_uidentity_cas_account (unit_id);

ALTER TABLE plugin_linapro_uidentity_cas_account
    ALTER COLUMN number TYPE VARCHAR(128),
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN pass_level TYPE BIGINT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN pass_level DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN pass_level DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_details (
    account_id BIGINT PRIMARY KEY,
    birthday TIMESTAMP NULL,
    email VARCHAR(128) NULL,
    gender BIGINT NULL,
    qq VARCHAR(128) NULL,
    wechat VARCHAR(128) NULL,
    idcard VARCHAR(128) NULL,
    avatar VARCHAR(128) NULL,
    source VARCHAR(128) NULL,
    nj BIGINT NULL,
    xymc VARCHAR(255) NULL,
    xydm VARCHAR(255) NULL,
    xq VARCHAR(255) NULL,
    xz BIGINT NULL,
    yjbysj BIGINT NULL,
    zymc VARCHAR(255) NULL,
    bjmc VARCHAR(255) NULL,
    face BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_email ON plugin_linapro_uidentity_cas_account_details (email);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_source ON plugin_linapro_uidentity_cas_account_details (source);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_details_deleted_at ON plugin_linapro_uidentity_cas_account_details (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_details
    ALTER COLUMN gender DROP DEFAULT,
    ALTER COLUMN nj DROP DEFAULT,
    ALTER COLUMN xz DROP DEFAULT,
    ALTER COLUMN yjbysj DROP DEFAULT,
    ALTER COLUMN face DROP DEFAULT;

ALTER TABLE plugin_linapro_uidentity_cas_account_details
    ALTER COLUMN email TYPE VARCHAR(128),
    ALTER COLUMN gender TYPE BIGINT,
    ALTER COLUMN qq TYPE VARCHAR(128),
    ALTER COLUMN wechat TYPE VARCHAR(128),
    ALTER COLUMN idcard TYPE VARCHAR(128),
    ALTER COLUMN avatar TYPE VARCHAR(128),
    ALTER COLUMN source TYPE VARCHAR(128),
    ALTER COLUMN nj TYPE BIGINT USING CASE WHEN nj::text ~ '^-?[0-9]+$' THEN nj::text::bigint ELSE NULL END,
    ALTER COLUMN xymc TYPE VARCHAR(255),
    ALTER COLUMN xydm TYPE VARCHAR(255),
    ALTER COLUMN xq TYPE VARCHAR(255),
    ALTER COLUMN xz TYPE BIGINT USING CASE WHEN xz::text ~ '^-?[0-9]+$' THEN xz::text::bigint ELSE NULL END,
    ALTER COLUMN yjbysj TYPE BIGINT USING CASE WHEN yjbysj::text ~ '^-?[0-9]+$' THEN yjbysj::text::bigint ELSE NULL END,
    ALTER COLUMN zymc TYPE VARCHAR(255),
    ALTER COLUMN bjmc TYPE VARCHAR(255),
    ALTER COLUMN face TYPE BIGINT USING CASE WHEN face::text ~ '^-?[0-9]+$' THEN face::text::bigint ELSE NULL END,
    ALTER COLUMN email DROP NOT NULL,
    ALTER COLUMN gender DROP NOT NULL,
    ALTER COLUMN qq DROP NOT NULL,
    ALTER COLUMN wechat DROP NOT NULL,
    ALTER COLUMN idcard DROP NOT NULL,
    ALTER COLUMN avatar DROP NOT NULL,
    ALTER COLUMN source DROP NOT NULL,
    ALTER COLUMN nj DROP NOT NULL,
    ALTER COLUMN xymc DROP NOT NULL,
    ALTER COLUMN xydm DROP NOT NULL,
    ALTER COLUMN xq DROP NOT NULL,
    ALTER COLUMN xz DROP NOT NULL,
    ALTER COLUMN yjbysj DROP NOT NULL,
    ALTER COLUMN zymc DROP NOT NULL,
    ALTER COLUMN bjmc DROP NOT NULL,
    ALTER COLUMN face DROP NOT NULL,
    ALTER COLUMN email DROP DEFAULT,
    ALTER COLUMN gender DROP DEFAULT,
    ALTER COLUMN qq DROP DEFAULT,
    ALTER COLUMN wechat DROP DEFAULT,
    ALTER COLUMN idcard DROP DEFAULT,
    ALTER COLUMN avatar DROP DEFAULT,
    ALTER COLUMN source DROP DEFAULT,
    ALTER COLUMN nj DROP DEFAULT,
    ALTER COLUMN xymc DROP DEFAULT,
    ALTER COLUMN xydm DROP DEFAULT,
    ALTER COLUMN xq DROP DEFAULT,
    ALTER COLUMN xz DROP DEFAULT,
    ALTER COLUMN yjbysj DROP DEFAULT,
    ALTER COLUMN zymc DROP DEFAULT,
    ALTER COLUMN bjmc DROP DEFAULT,
    ALTER COLUMN face DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    account_count BIGINT NULL,
    admin_count BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_name ON plugin_linapro_uidentity_cas_containers (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_containers_deleted_at ON plugin_linapro_uidentity_cas_containers (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_containers
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN account_count DROP NOT NULL,
    ALTER COLUMN admin_count DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN account_count DROP DEFAULT,
    ALTER COLUMN admin_count DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_name ON plugin_linapro_uidentity_cas_groups (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_groups_deleted_at ON plugin_linapro_uidentity_cas_groups (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_groups
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    code BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_name ON plugin_linapro_uidentity_cas_units (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_code ON plugin_linapro_uidentity_cas_units (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_units_deleted_at ON plugin_linapro_uidentity_cas_units (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_units
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN code DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN code DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    alias VARCHAR(128) NULL,
    client_id VARCHAR(128) NULL,
    secret_key VARCHAR(128) NULL,
    access_model VARCHAR(128) NULL,
    status BIGINT NULL,
    callback_url VARCHAR(128) NULL,
    whitelist TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_name ON plugin_linapro_uidentity_cas_applications (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_client_id ON plugin_linapro_uidentity_cas_applications (client_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_status ON plugin_linapro_uidentity_cas_applications (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_applications_deleted_at ON plugin_linapro_uidentity_cas_applications (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_applications
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN alias TYPE VARCHAR(128),
    ALTER COLUMN client_id TYPE VARCHAR(128),
    ALTER COLUMN secret_key TYPE VARCHAR(128),
    ALTER COLUMN access_model TYPE VARCHAR(128),
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN callback_url TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN alias DROP NOT NULL,
    ALTER COLUMN client_id DROP NOT NULL,
    ALTER COLUMN secret_key DROP NOT NULL,
    ALTER COLUMN access_model DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN callback_url DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN alias DROP DEFAULT,
    ALTER COLUMN client_id DROP DEFAULT,
    ALTER COLUMN secret_key DROP DEFAULT,
    ALTER COLUMN access_model DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT,
    ALTER COLUMN callback_url DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_group (
    account_id BIGINT NOT NULL,
    groups_id BIGINT NOT NULL,
    PRIMARY KEY (account_id, groups_id)
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_group_groups_id ON plugin_linapro_uidentity_cas_account_group (groups_id);

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'plugin_linapro_uidentity_cas_account_unit'
          AND column_name = 'units_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'plugin_linapro_uidentity_cas_account_unit'
          AND column_name = 'unit_id'
    ) THEN
        ALTER TABLE plugin_linapro_uidentity_cas_account_unit RENAME COLUMN units_id TO unit_id;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_account_id ON plugin_linapro_uidentity_cas_account_unit (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_unit_id ON plugin_linapro_uidentity_cas_account_unit (unit_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_uidentity_cas_account_unit_unique ON plugin_linapro_uidentity_cas_account_unit (account_id, unit_id);

ALTER TABLE plugin_linapro_uidentity_cas_account_unit
    ALTER COLUMN account_id TYPE BIGINT,
    ALTER COLUMN unit_id TYPE BIGINT,
    ALTER COLUMN account_id SET NOT NULL,
    ALTER COLUMN unit_id SET NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN unit_id DROP DEFAULT;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS units_id;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS created_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS updated_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS create_by;
ALTER TABLE plugin_linapro_uidentity_cas_account_unit DROP COLUMN IF EXISTS update_by;
DROP INDEX IF EXISTS idx_uidentity_cas_account_unit_units_id;
DROP INDEX IF EXISTS idx_uidentity_cas_account_unit_deleted_at;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    give_account_id BIGINT NULL,
    empowered_account_id BIGINT NULL,
    app_id BIGINT NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_give_account ON plugin_linapro_uidentity_cas_account_app_role (give_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_empowered_account ON plugin_linapro_uidentity_cas_account_app_role (empowered_account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_app_id ON plugin_linapro_uidentity_cas_account_app_role (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_role_deleted_at ON plugin_linapro_uidentity_cas_account_app_role (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_app_role
    ALTER COLUMN give_account_id DROP NOT NULL,
    ALTER COLUMN empowered_account_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN give_account_id DROP DEFAULT,
    ALTER COLUMN empowered_account_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    app_id BIGINT NULL,
    account_id BIGINT NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_app_id ON plugin_linapro_uidentity_cas_account_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_account_id ON plugin_linapro_uidentity_cas_account_app_blacklist (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_account_app_blacklist (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_app_blacklist
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN account_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_group_app_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    app_id BIGINT NULL,
    group_id BIGINT NULL,
    effect_at TIMESTAMP NULL,
    expire_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_app_id ON plugin_linapro_uidentity_cas_group_app_blacklist (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_group_id ON plugin_linapro_uidentity_cas_group_app_blacklist (group_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_group_app_blacklist_deleted_at ON plugin_linapro_uidentity_cas_group_app_blacklist (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_group_app_blacklist
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN group_id DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN group_id DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_pass_ruler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NULL,
    capital BIGINT NULL,
    lower BIGINT NULL,
    number BIGINT NULL,
    symbol BIGINT NULL,
    length BIGINT NULL,
    "interval" BIGINT NULL,
    interval_status BIGINT NULL,
    status BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_name ON plugin_linapro_uidentity_cas_pass_ruler (name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_status ON plugin_linapro_uidentity_cas_pass_ruler (status);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_pass_ruler_deleted_at ON plugin_linapro_uidentity_cas_pass_ruler (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_pass_ruler
    ALTER COLUMN name TYPE VARCHAR(128),
    ALTER COLUMN interval_status TYPE BIGINT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN capital DROP NOT NULL,
    ALTER COLUMN lower DROP NOT NULL,
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN symbol DROP NOT NULL,
    ALTER COLUMN length DROP NOT NULL,
    ALTER COLUMN "interval" DROP NOT NULL,
    ALTER COLUMN interval_status DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN name DROP DEFAULT,
    ALTER COLUMN capital DROP DEFAULT,
    ALTER COLUMN lower DROP DEFAULT,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN symbol DROP DEFAULT,
    ALTER COLUMN length DROP DEFAULT,
    ALTER COLUMN "interval" DROP DEFAULT,
    ALTER COLUMN interval_status DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(128) NULL,
    type VARCHAR(128) NULL,
    content TEXT NULL,
    status BIGINT NULL,
    resp_msg TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_phone ON plugin_linapro_uidentity_cas_sms (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_type ON plugin_linapro_uidentity_cas_sms (type);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_sms_deleted_at ON plugin_linapro_uidentity_cas_sms (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_sms
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN type TYPE VARCHAR(128),
    ALTER COLUMN content TYPE TEXT,
    ALTER COLUMN status TYPE BIGINT,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN type DROP NOT NULL,
    ALTER COLUMN content DROP NOT NULL,
    ALTER COLUMN status DROP NOT NULL,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN type DROP DEFAULT,
    ALTER COLUMN content DROP DEFAULT,
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_cas_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NULL,
    choice_account_id BIGINT NULL,
    app_id BIGINT NULL,
    ipaddr VARCHAR(255) NULL,
    login_location VARCHAR(255) NULL,
    browser VARCHAR(255) NULL,
    os VARCHAR(255) NULL,
    platform VARCHAR(255) NULL,
    login_time TIMESTAMP NULL,
    remark VARCHAR(255) NULL,
    msg VARCHAR(255) NULL,
    login_type VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_account_id ON plugin_linapro_uidentity_cas_cas_login_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_app_id ON plugin_linapro_uidentity_cas_cas_login_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_login_time ON plugin_linapro_uidentity_cas_cas_login_log (login_time);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_cas_login_log_deleted_at ON plugin_linapro_uidentity_cas_cas_login_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_cas_login_log
    ALTER COLUMN ipaddr TYPE VARCHAR(255),
    ALTER COLUMN browser TYPE VARCHAR(255),
    ALTER COLUMN os TYPE VARCHAR(255),
    ALTER COLUMN platform TYPE VARCHAR(255),
    ALTER COLUMN login_type TYPE VARCHAR(255),
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN choice_account_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN ipaddr DROP NOT NULL,
    ALTER COLUMN login_location DROP NOT NULL,
    ALTER COLUMN browser DROP NOT NULL,
    ALTER COLUMN os DROP NOT NULL,
    ALTER COLUMN platform DROP NOT NULL,
    ALTER COLUMN remark DROP NOT NULL,
    ALTER COLUMN msg DROP NOT NULL,
    ALTER COLUMN login_type DROP NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN choice_account_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN ipaddr DROP DEFAULT,
    ALTER COLUMN login_location DROP DEFAULT,
    ALTER COLUMN browser DROP DEFAULT,
    ALTER COLUMN os DROP DEFAULT,
    ALTER COLUMN platform DROP DEFAULT,
    ALTER COLUMN remark DROP DEFAULT,
    ALTER COLUMN msg DROP DEFAULT,
    ALTER COLUMN login_type DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    app_id BIGINT NULL,
    redirect_uri VARCHAR(256) NULL,
    scope VARCHAR(256) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_user_id ON plugin_linapro_uidentity_cas_oauth_log (user_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_app_id ON plugin_linapro_uidentity_cas_oauth_log (app_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth_log_deleted_at ON plugin_linapro_uidentity_cas_oauth_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_oauth_log
    ALTER COLUMN redirect_uri TYPE VARCHAR(256),
    ALTER COLUMN scope TYPE VARCHAR(256),
    ALTER COLUMN user_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL,
    ALTER COLUMN redirect_uri DROP NOT NULL,
    ALTER COLUMN scope DROP NOT NULL,
    ALTER COLUMN user_id DROP DEFAULT,
    ALTER COLUMN app_id DROP DEFAULT,
    ALTER COLUMN redirect_uri DROP DEFAULT,
    ALTER COLUMN scope DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_oauth2_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expired_at BIGINT NULL,
    code TEXT NULL,
    access TEXT NULL,
    refresh TEXT NULL,
    data TEXT NULL
);

ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS created_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS updated_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS create_by;
ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token DROP COLUMN IF EXISTS update_by;

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_code ON plugin_linapro_uidentity_cas_oauth2_token (code);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_access ON plugin_linapro_uidentity_cas_oauth2_token (access);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_refresh ON plugin_linapro_uidentity_cas_oauth2_token (refresh);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_oauth2_token_expired_at ON plugin_linapro_uidentity_cas_oauth2_token (expired_at);
DROP INDEX IF EXISTS idx_uidentity_cas_oauth2_token_deleted_at;

ALTER TABLE plugin_linapro_uidentity_cas_oauth2_token
    ALTER COLUMN code TYPE TEXT,
    ALTER COLUMN access TYPE TEXT,
    ALTER COLUMN refresh TYPE TEXT,
    ALTER COLUMN expired_at DROP NOT NULL,
    ALTER COLUMN code DROP NOT NULL,
    ALTER COLUMN access DROP NOT NULL,
    ALTER COLUMN refresh DROP NOT NULL,
    ALTER COLUMN expired_at DROP DEFAULT,
    ALTER COLUMN code DROP DEFAULT,
    ALTER COLUMN access DROP DEFAULT,
    ALTER COLUMN refresh DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NULL,
    table_name VARCHAR(128) NULL,
    action VARCHAR(128) NULL,
    data_old TEXT NULL,
    data_new TEXT NULL,
    err_msg TEXT NULL,
    err_number TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    create_by BIGINT NULL,
    update_by BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_account_id ON plugin_linapro_uidentity_cas_account_change_log (account_id);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_table_name ON plugin_linapro_uidentity_cas_account_change_log (table_name);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_change_log_deleted_at ON plugin_linapro_uidentity_cas_account_change_log (deleted_at);

ALTER TABLE plugin_linapro_uidentity_cas_account_change_log
    ALTER COLUMN table_name TYPE VARCHAR(128),
    ALTER COLUMN action TYPE VARCHAR(128),
    ALTER COLUMN err_number TYPE TEXT USING err_number::text,
    ALTER COLUMN account_id DROP NOT NULL,
    ALTER COLUMN table_name DROP NOT NULL,
    ALTER COLUMN action DROP NOT NULL,
    ALTER COLUMN err_number DROP NOT NULL,
    ALTER COLUMN account_id DROP DEFAULT,
    ALTER COLUMN table_name DROP DEFAULT,
    ALTER COLUMN action DROP DEFAULT,
    ALTER COLUMN err_number DROP DEFAULT;

CREATE TABLE IF NOT EXISTS plugin_linapro_uidentity_cas_account_active_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(128) NULL,
    phone VARCHAR(128) NULL,
    wechat VARCHAR(128) NULL,
    created_at TIMESTAMP NULL,
    type BIGINT NULL
);

CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_number ON plugin_linapro_uidentity_cas_account_active_log (number);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_phone ON plugin_linapro_uidentity_cas_account_active_log (phone);
CREATE INDEX IF NOT EXISTS idx_uidentity_cas_account_active_log_type ON plugin_linapro_uidentity_cas_account_active_log (type);

ALTER TABLE plugin_linapro_uidentity_cas_account_active_log
    ALTER COLUMN number TYPE VARCHAR(128),
    ALTER COLUMN phone TYPE VARCHAR(128),
    ALTER COLUMN wechat TYPE VARCHAR(128),
    ALTER COLUMN number DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL,
    ALTER COLUMN wechat DROP NOT NULL,
    ALTER COLUMN type DROP NOT NULL,
    ALTER COLUMN number DROP DEFAULT,
    ALTER COLUMN phone DROP DEFAULT,
    ALTER COLUMN wechat DROP DEFAULT,
    ALTER COLUMN type DROP DEFAULT;

INSERT INTO plugin_linapro_uidentity_cas_pass_ruler (
    name, capital, lower, number, symbol, length, "interval", interval_status, status, created_at, updated_at
)
SELECT 'default', 0, 0, 1, 0, 8, 90, 1, 1, NOW(), NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM plugin_linapro_uidentity_cas_pass_ruler WHERE name = 'default' AND deleted_at IS NULL
);
